name: str-optimizer-backend
services:
- name: api
  source_dir: /
  github:
    repo: YOUR_GITHUB_USERNAME/str-optimizer-backend
    branch: main
  run_command: gunicorn --worker-tmp-dir /dev/shm --config gunicorn_config.py app:app
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  health_check:
    http_path: /health
  envs:
  - key: FLASK_ENV
    value: production
  - key: PORT
    value: "8080"
  - key: HOST
    value: "0.0.0.0"
  # Add your other environment variables in the DO console 