# Use proven wkhtmltopdf image - guaranteed to work
FROM surnet/alpine-wkhtmltopdf:3.19.1-0.12.6-small as wkhtmltopdf
FROM python:3.11-slim

# Copy wkhtmltopdf from proven image
COPY --from=wkhtmltopdf /bin/wkhtmltopdf /usr/local/bin/wkhtmltopdf

# Install system dependencies
RUN apt-get update && apt-get install -y \
    xvfb \
    fonts-liberation \
    fonts-noto-color-emoji \
    fonts-noto-cjk \
    fontconfig \
    libx11-6 \
    libxext6 \
    libxrender1 \
    libjpeg62-turbo \
    libpng16-16 \
    libssl3 \
    && rm -rf /var/lib/apt/lists/*

# Python is already properly configured in python:3.11-slim

# Set working directory
WORKDIR /workspace

# Copy requirements and install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY . .

# Verify wkhtmltopdf is available and can generate PDFs
RUN python -c "
import os
import sys
import subprocess
import tempfile

print('=== WKHTMLTOPDF VERIFICATION ===')

# Test wkhtmltopdf availability
try:
    result = subprocess.run(['/usr/local/bin/wkhtmltopdf', '--version'], capture_output=True, text=True, timeout=10)
    if result.returncode == 0:
        print(f'✅ wkhtmltopdf found: {result.stdout.strip()}')
    else:
        print('❌ wkhtmltopdf not working')
        sys.exit(1)
except Exception as e:
    print(f'❌ wkhtmltopdf check failed: {e}')
    sys.exit(1)

# Test PDF generation capability
try:
    # Create test HTML
    test_html = '''
    <html>
    <head>
        <title>Test PDF</title>
        <style>
            body { font-family: Arial, sans-serif; margin: 40px; }
            h1 { color: #2563eb; }
        </style>
    </head>
    <body>
        <h1>wkhtmltopdf Test</h1>
        <p>This is a test PDF generated by wkhtmltopdf in Docker.</p>
    </body>
    </html>
    '''
    
    with tempfile.NamedTemporaryFile(mode='w', suffix='.html', delete=False) as html_file:
        html_file.write(test_html)
        html_path = html_file.name
    
    with tempfile.NamedTemporaryFile(suffix='.pdf', delete=False) as pdf_file:
        pdf_path = pdf_file.name
    
         # Test PDF generation
     cmd = [
         'xvfb-run', '-a', '--server-args=-screen 0 1024x768x24',
         '/usr/local/bin/wkhtmltopdf', 
         '--page-size', 'A4',
         '--margin-top', '0.75in',
         html_path,
         pdf_path
     ]
    
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
    
    if result.returncode == 0 and os.path.exists(pdf_path):
        file_size = os.path.getsize(pdf_path)
        print(f'✅ PDF generation test successful ({file_size:,} bytes)')
        
        # Clean up
        os.unlink(html_path)
        os.unlink(pdf_path)
    else:
        print(f'❌ PDF generation test failed: {result.stderr}')
        sys.exit(1)
        
except Exception as e:
    print(f'❌ PDF test failed: {e}')
    sys.exit(1)

print('🎉 WKHTMLTOPDF PDF SYSTEM READY!')
"

# Expose port
EXPOSE 8080

# Start command
CMD ["gunicorn", "--bind", "0.0.0.0:8080", "--workers", "1", "--timeout", "120", "wsgi:application"] 